name: XAI_project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - altair
  - bitarray
  - deap
  - dice-ml
  - jupyter=1.0
  - jupyterlab
  - matplotlib=3.8
  - numpy=1.24
  - pandas=2.1
  - pip=23.3
  - python=3.11
  - pytorch=2.1
  - scikit-learn=1.3
  - scipy=1.11
  - seaborn=0.13
  - shap=0.42
  - lime
  - tqdm
  - pip:
    - pytorch-tabnet